# Generated by Django 2.0.5 on 2018-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
